backend:
  name: git-gateway
  branch: main 

media_folder: "public/images" 
public_folder: "/images" 

collections:
  - name: "projects" 
    label: "Projects" 
    folder: "projects" 
    extension: "json"
    editor:
      preview: false
    create: true 
    slug: "{{year}}--{{month}}-{{slug}}" 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Categories", name: "category", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}